package ex.devs.exbooks.utils

const val HEADER_TOKEN = "AAAA7wPU7Bs:APA91bEScgitbNydwjBLbcW-dGTJLp5DdQ_kMQxynQLrJKYqDOBNjYGsNk7xxGYLw-cRzmGKF_0R_cuwr7e4VJ88TivKMgB44BeQDW4mlZfZsd-JkXSRFYxDfRYw0PgmldAneW8l987U"